services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  web:
    build: .
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  bot:
    build: .
    command: python3 -m bot polling
    volumes:
      - .:/app
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - /etc/letsencrypt:/etc/letsencrypt  # Mount certs
    ports:
      - "80:80"
      - "443:443"  # Expose HTTPS
    depends_on:
      - web
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
